# Setup
title:               IMDAVI
tagline:             'IMDAVI (IMmersive DAta VIsualization)'
description:         'A research group study how to use immersive technologies for data visualization and analysis.' 
url:                 https://imdavi.github.io
baseurl:             ''
paginate:            5
paginate_path:       "/blog/page:num/"
permalink:           pretty

# About/contact
author:
  name:              Felipe Pedroso
  url:               https://twitter.com/felipeapedroso
  email:             felipe.pedroso@live.com

# Gems
plugins:
  - jekyll-paginate
  - github-pages

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

repository:            imdavi/imdavi.github.io